### ISSUE TITLE
Nginx 리버스 프록시를 적용한다

### ISSUE THREAD

**Issue by vectorch9** [DayByQuest/backend#125]
## 🗒 Summary
- 

## ✅ Todo
- [x] 배포 및 리버스 프록시 적용
- [x] URL에 따라 S3, 스프링 서버로 분기하도록 설정
- [x] SSE 관련 설정

## 💡 More
-
