### ISSUE TITLE
요청사항을 반영한다

### ISSUE THREAD

**Issue by vectorch9** [DayByQuest/backend#130]
## 🗒 Summary
- 

## ✅ Todo
- [x] 그룹 프로필 조회 시 가입 여부
- [x] 그룹 퀘스트 조회시 활성 상태인 퀘스트만 조회
- [x] `followingCount` 가 `0`으로 고정되는 버그 수정
- [x] `follow`, `block`의 대상이 자기 자신인지 검증

## 💡 More
-
